diff --git a/trunk/user/www/Makefile b/trunk/user/www/Makefile
index d8b817d3c3..f5ab7f0f4f 100644
--- a/trunk/user/www/Makefile
+++ b/trunk/user/www/Makefile
@@ -9,7 +9,7 @@ include $(ROOTDIR)/user/shared/boards.mk
 PROJECT_HOME_URL="https:\/\/bitbucket.org\/padavan\/rt-n56u\/"
 PROJECT_HOME_URL_MOD="https:\/\/github.com\/hanwckf\/rt-n56u\/"
 
-LABEL_COPYRIGHT_TEXT='© 2011-2021 <a href="https:\/\/bitbucket.org\/padavan\/rt-n56u" target="blank">Padavan<\/a> \& N56U project community \& by <a href="https:\/\/github.com\/hanwckf\/rt-n56u" target="blank">hanwckf<\/a>'
+LABEL_COPYRIGHT_TEXT='© 2011-2026 <a href="https:\/\/bitbucket.org\/padavan\/rt-n56u" target="blank">Padavan<\/a> \& N56U project community \& by <a href="http:\/\/www.techmes.cn" target="blank">游灵<\/a>'
 
 BOARD_PATTERN=s/ZVMODELVZ/$(CONFIG_FIRMWARE_PRODUCT_ID)/g
 COPYR_PATTERN=s/ZVCOPYRVZ/$(LABEL_COPYRIGHT_TEXT)/g
@@ -131,6 +131,7 @@ endif
 	rm -f $(ROMFS_DIR)/www/bootstrap/js/jquery.backgroundpos.min.js
 	rm -f $(ROMFS_DIR)/www/bootstrap/js/jquery.easing.1.3.js
 	rm -f $(ROMFS_DIR)/www/bootstrap/css/bootstrap.css
+	rm -f $(ROMFS_DIR)/www/Advanced_System_Info.asp
 ifeq ($(BOARD_HAS_2G_RADIO),0)
 	rm -f $(INSTALLDIR)/www/Advanced_ACL2g_Content.asp
 	rm -f $(INSTALLDIR)/www/Advanced_WAdvanced2g_Content.asp
@@ -199,6 +200,11 @@ ifneq ($(CONFIG_FIRMWARE_INCLUDE_SHADOWSOCKS),y)
 	rm -f $(INSTALLDIR)/www/Shadowsocks_action.asp
 	rm -f $(INSTALLDIR)/www/Shadowsocks_log.asp
 endif
+ifneq ($(CONFIG_FIRMWARE_INCLUDE_OPENVPN_WEBUI),y)
+	rm -f $(INSTALLDIR)/www/vpn_clients.asp
+	rm -f $(INSTALLDIR)/www/vpnsrv.asp
+	rm -f $(INSTALLDIR)/www/vpncli.asp
+endif
 
 clean:
 	@echo "Clean www romfs"
