THISDIR = $(shell pwd)
all:

clean:

romfs:
	$(ROMFSINST) -p +x+r /usr/sbin/vnt-cli
	$(ROMFSINST) -p +x+r /usr/sbin/vnt
	$(ROMFSINST) -p +x+r /usr/sbin/start
#	$(ROMFSINST) -p +x+r /var/judge.sh
#	$(ROMFSINST) -p +x+r /usr/sbin/start
